#!/usr/bin/env bash

set -euo pipefail

# plot_pcb () {
# 	tempdir=$(mktemp -d)

# 	kicad-cli pcb export pdf \
# 		--include-border-title \
# 		--layers "F.Cu,Edge.Cuts" \
# 		"source/$1/$1.kicad_pcb" \
# 		--output "$tempdir/$1-top.pdf"

# 	kicad-cli pcb export pdf \
# 		--include-border-title \
# 		--layers "B.Cu,Edge.Cuts" \
# 		"source/$1/$1.kicad_pcb" \
# 		--output "$tempdir/$1-bottom.pdf"

# 	pdfunite "$tempdir/$1-top.pdf" "$tempdir/$1-bottom.pdf" "exports/plots/$1-pcb.pdf" 2>/dev/null

# 	git add "exports/plots/$1-pcb.pdf"

# 	rm -r $tempdir
# }

# plot_sch () {
# 	kicad-cli sch export pdf \
# 		"source/$1/$1.kicad_sch" \
# 		--output "exports/plots/$1-sch.pdf"

# 	git add "exports/plots/$1-sch.pdf"
# }

files_added=`git diff --cached --name-status`
project_paths=`find source -mindepth 1 -maxdepth 1 -type d`

while read -r project_path; do
	project_name=`echo $project_path | sed -e 's/^source\///g'`

	re="$project_path.*\.kicad_pcb"
	if [[ $files_added =~ $re ]]
	then
		make "exports/plots/$project_name-pcb.pdf"
		make "production/gbr/$project_name.zip"
		git add "exports/plots/$project_name-pcb.pdf"
		git add "production/gbr/$project_name"
	fi

	re="$project_path.*\.kicad_sch"
	if [[ $files_added =~ $re ]]
	then
		make "exports/plots/$project_name-sch.pdf"
		git add "exports/plots/$project_name-sch.pdf"
	fi
done <<< "$project_paths"
