M48
; DRILL file {KiCad 6.0.9} date 2023-01-31T15:22:15 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-31T15:22:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0935
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1024
%
G90
G05
T1
X8.3Y-2.96
X8.3Y-3.04
X8.5Y-3.0
T2
X6.1811Y-4.8031
X6.1811Y-4.9449
X6.4173Y-4.8031
X6.4173Y-4.9449
T3
X8.375Y-2.9
X8.375Y-3.1
X8.5Y-2.9
X8.5Y-3.1
T4
X5.7638Y-2.0236
X5.9449Y-2.0236
T0
M30
